The ability to add exclusions list
alexzel/bad-words-next pull request #18
Opened 2023-10-11 14:38 UTC by AleX83Xpert

Hello! I'd like to use some exclusions. This PR brings such functionality.

todo list:
- [x] the main functionality
- [x] add test
- [x] update readme

2023-10-12 19:24 UTC, alexzel requested changes

2023-10-12 19:24 UTC, alexzel commented on src/index.ts
> +   * @param {boolean} isWord
Do we really need this flag? Can the feature be implemented without it?

2023-10-12 19:24 UTC, alexzel commented on src/index.ts
> +        if (this.regexp(exclusion).test(str)) {
As we consider each item as a pattern, maybe we need to have a test for that as well and update the readme example to have a pattern string like `sh+it+`

2023-10-12 19:24 UTC, alexzel commented on src/index.ts
> +        if (this.regexp(exclusion).test(str)) {
Also, I would pre-process exclusions in the constructor to call `this.regexp` only once instead of on each check call. Besides that, I think we need to take into consideration lookalikes somehow.

2023-10-13 06:57 UTC, AleX83Xpert commented on README.md
> +const badwords = new BadWordsNext({ data: en }, { exclusions: ['sh!tt'] })
Oops, sorry. Fixed :)

2023-10-13 07:02 UTC, AleX83Xpert commented on src/index.ts
> +   * @param {boolean} isWord
The `check` function was called for a whole string and for a particular word. The first call is used to detect if deep checking is needed or not. So, I decided to add a boolean variable to detect the call purpose.

Now I've refactored this function to eliminate the `isWord` parameter.

2023-10-13 07:04 UTC, AleX83Xpert commented on src/index.ts
> +        if (this.regexp(exclusion).test(str)) {
You right. Now we remove all lookalikes before checking.
The building of regexps for exclusions was moved to the constructor and called once.

2023-10-13 07:06 UTC, AleX83Xpert commented on src/index.ts
> +   * @param {boolean} isWord
Also, I've added the test to be sure that deep checking by words is not called for the case when input text is clean.

2023-11-09 07:51 UTC, AleX83Xpert commented
Hi @alexzel! Any update?

2024-04-07 19:28 UTC, alexzel commented
Sorry for the delay, but I remember that after running the benchmark it was significantly slower specifically for the `filter` calls.. I'll take a look and think how it all can be improved..

2024-04-07 20:38 UTC, alexzel approved these changes

2024-04-07 20:41 UTC, alexzel commented
I have added some improvements including caching `preCheck` calls, so the benchmark should shine again.

2024-04-07 20:42 UTC, merged

2024-04-07 20:48 UTC, alexzel commented
v2.3.0 should include these changes. Thanks for the contribution!